# Python spending app

In [3]:
import pandas as pd
import numpy as np
import plotly.express as px

In [4]:
transactions = pd.read_excel(
    "data/transactions.xls",
    skiprows= 2
)

In [3]:
transactions

,Date operation,Categorie operation,Sous Categorie operation,Libelle operation,Montant operation,Pointage operation,Commentaire operation
0,02-04-2026,Revenus,Virement reçu,VIREMENT DE MME KATHERINE COUTIN MOTIF: PAYME...,35.00,NaN,NaN
1,02-04-2026,À catégoriser,Chèque émis,CHEQUE 9632276,-30.00,NaN,NaN
2,02-04-2026,Banque,Frais bancaires,COMMISSIONS COTISATION A UNE OFFRE GROUPEE DE ...,-11.04,NaN,NaN
3,02-04-2026,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB CARREFOUR DU 31/03/26 A PARIS - CA...,-3.90,NaN,NaN
4,31-03-2026,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00,NaN,NaN
...,...,...,...,...,...,...,...
506,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
507,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
508,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
509,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
510,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN

In [3]:
columns = transactions.columns.to_list()

In [4]:
columns

['Date operation',
 'Categorie operation',
 'Sous Categorie operation',
 'Libelle operation',
 'Montant operation',
 'Pointage operation',
 'Commentaire operation']

In [5]:
col_map = {'Date operation' : 'date',
           'Categorie operation' : 'category',
           'Sous Categorie operation' : 'subcategory',
           'Libelle operation' : 'label',
           'Montant operation' : 'amount',
           'Pointage operation' : 'status',
           'Commentaire operation' : 'comment'} 

transactions = transactions.rename(columns= col_map)

transactions

,date,category,subcategory,label,amount,status,comment
0,02-04-2026,Revenus,Virement reçu,VIREMENT DE MME KATHERINE COUTIN MOTIF: PAYME...,35.00,NaN,NaN
1,02-04-2026,Autres Dépenses,"Avocats, notaires, comptabilité",CHEQUE 9632276,-30.00,NaN,NaN
2,02-04-2026,Banque,Frais bancaires,COMMISSIONS COTISATION A UNE OFFRE GROUPEE DE ...,-11.04,NaN,NaN
3,02-04-2026,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB CARREFOUR DU 31/03/26 A PARIS - CA...,-3.90,NaN,NaN
4,31-03-2026,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00,NaN,NaN
...,...,...,...,...,...,...,...
506,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
507,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
508,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
509,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN
510,03-03-2025,Revenus,À catégoriser,NaN,0.00,NaN,NaN

In [7]:
transactions.columns.tolist()

['date', 'category', 'subcategory', 'label', 'amount', 'status', 'comment']

In [8]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 511 entries, 0 to 510
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         511 non-null    str
 1   category     511 non-null    str
 2   subcategory  511 non-null    str
 3   label        493 non-null    str
 4   amount       511 non-null    float64
 5   status       0 non-null      float64
 6   comment      0 non-null      float64
dtypes: float64(3), str(4)
memory usage: 83.9 KB

In [6]:
transactions.to_csv("data/test.csv")

In [7]:
tester = transactions.copy()

In [8]:
tester['subcategory'].unique()

<ArrowStringArray>
[                       'Virement reçu',
      'Avocats, notaires, comptabilité',
                      'Frais bancaires',
            'Alimentation, supermarché',
 'Divertissements, sorties culturelles',
                    'Restaurants, bars',
          'Achat multimédia, high-tech',
                     'Achats, shopping',
                    'Voyages, vacances',
                              'Cadeaux',
                            'Carburant',
                        'Stationnement',
                 'Transports en commun',
                        'Virement émis',
                      'Dons caritatifs',
                          'Chèque reçu',
                 'Aides et allocations',
                            'Pharmacie',
      'Billet d'avion, billet de train',
               'Musique, livres, films',
                        'Remboursement',
             'Vie quotidienne - Autres',
          'Coiffeur, cosmétique, soins',
          'Loisirs et sorties - Autres',
                          'Habillement',
                  'Impôt sur le revenu',
                      'Banque - Autres',
                              'Épargne',
       'Salaires et revenus d'activité',
               'Bricolage et jardinage',
                        'Frais postaux',
                            'Téléphone',
                    'Retrait d'espèces',
                                'Loyer',
      'Mobilier, electroménager, déco.',
                        'À catégoriser']
Length: 36, dtype: str

In [9]:
def is_savings(row):
    if row['amount'] < 0 and row['category'] == 'Banque':
        return 'épargne'
    elif row['amount'] < 0 :
        return 'dépense'
    else:
        return 'revenu'
    
tester['label'] = tester.apply(is_savings, axis= 1)

In [10]:
tester[tester['label'] == 'épargne']

           date category      subcategory    label   amount  status  comment
2    02-04-2026   Banque  Frais bancaires  épargne   -11.04     NaN      NaN
44   03-03-2026   Banque  Frais bancaires  épargne   -11.04     NaN      NaN
83   03-02-2026   Banque  Frais bancaires  épargne   -11.04     NaN      NaN
116  05-01-2026   Banque  Frais bancaires  épargne   -10.43     NaN      NaN
143  08-12-2025   Banque  Banque - Autres  épargne  -150.00     NaN      NaN
158  02-12-2025   Banque  Frais bancaires  épargne   -10.43     NaN      NaN
159  28-11-2025   Banque  Banque - Autres  épargne  -200.00     NaN      NaN
173  17-11-2025   Banque  Banque - Autres  épargne  -200.00     NaN      NaN
194  04-11-2025   Banque  Frais bancaires  épargne   -10.43     NaN      NaN
204  30-10-2025   Banque          Épargne  épargne -2300.00     NaN      NaN
223  02-10-2025   Banque  Frais bancaires  épargne   -10.43     NaN      NaN
238  03-09-2025   Banque          Épargne  épargne -1670.00     NaN      NaN
240  02-09-2025   Banque  Frais bancaires  épargne   -10.43     NaN      NaN
244  29-08-2025   Banque  Frais bancaires  épargne   -24.00     NaN      NaN
248  18-08-2025   Banque          Épargne  épargne -6000.00     NaN      NaN
250  04-08-2025   Banque  Frais bancaires  épargne    -8.77     NaN      NaN
251  31-07-2025   Banque          Épargne  épargne   -30.00     NaN      NaN
280  02-07-2025   Banque  Frais bancaires  épargne    -8.77     NaN      NaN
354  03-06-2025   Banque  Frais bancaires  épargne    -8.77     NaN      NaN
392  05-05-2025   Banque  Frais bancaires  épargne    -8.77     NaN      NaN
411  11-04-2025   Banque  Banque - Autres  épargne  -150.00     NaN      NaN
416  07-04-2025   Banque  Banque - Autres  épargne  -300.00     NaN      NaN
427  02-04-2025   Banque  Frais bancaires  épargne    -8.77     NaN      NaN

In [11]:
tester = pd.read_excel("data/transactions.xls",
                       skiprows= 2
)

# renaming columns
col_map = {'Date operation' : 'date',
           'Categorie operation' : 'category',
           'Sous Categorie operation' : 'subcategory',
           'Libelle operation' : 'label',
           'Montant operation' : 'amount',
           'Pointage operation' : 'status',
           'Commentaire operation' : 'comment'} 

tester = tester.rename(columns= col_map)

# removing useless columns and NaN rows
tester = tester.drop(columns= ['status', 'comment'])
tester = tester.dropna()

tester.to_excel("data/transactions2.xlsx", index= False)

In [12]:
transactions = pd.read_excel("data/transactions.xlsx")

#this is our income
income = transactions[transactions['amount'] > 0]
#some of the spending is actually going towards our savings account. We don't want to count it as an expense
negative = transactions[transactions['amount'] < 0]

savings = negative[negative['subcategory'] == 'Épargne']
expense = negative[negative['subcategory'] != 'Épargne']

In [15]:
negative

,date,category,subcategory,label,amount
1,02-04-2026,À catégoriser,Chèque émis,CHEQUE 9632276,-30.00
2,02-04-2026,Banque,Frais bancaires,COMMISSIONS COTISATION A UNE OFFRE GROUPEE DE ...,-11.04
3,02-04-2026,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB CARREFOUR DU 31/03/26 A PARIS - CA...,-3.90
4,31-03-2026,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00
6,31-03-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB SONNY S PIZZA DU 27/03/26 A PARIS ...,-35.00
...,...,...,...,...,...
488,10-03-2025,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LE LOBBY BAR DU 07/03/25 A LILLE -...,-12.00
489,10-03-2025,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB PHOENICIA DU 09/03/25 A LILLE - CA...,-9.50
490,10-03-2025,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-5.00
491,10-03-2025,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB MAXICOFFEE NORD DU 07/03/25 A NEUV...,-0.70
492,10-03-2025,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-0.30

In [14]:
expense = negative[negative['subcategory'] != 'Épargne']

expense[expense['category'] == 'À catégoriser']

,date,category,subcategory,label,amount
27,16-03-2026,À catégoriser,Virement émis,VIREMENT INSTANTANE EMIS VERS KATHERINE C - MO...,-15.00
131,23-12-2025,À catégoriser,Virement émis,VIREMENT INSTANTANE EMIS VERS JULIA-MARIE P - ...,-50.00
195,03-11-2025,À catégoriser,Virement émis,VIREMENT VERS MR PENNER-LACOMPTE DOUGLAS - MOT...,-1000.00
201,31-10-2025,À catégoriser,Virement émis,VIREMENT VERS MR PENNER-LACOMPTE DOUGLAS - MOT...,-2000.00
230,22-09-2025,À catégoriser,Virement émis,VIREMENT INSTANTANE EMIS VERS DOUGLAS PENNER -...,-1000.00
232,22-09-2025,À catégoriser,Virement émis,VIREMENT INSTANTANE EMIS VERS DOUGLAS PENNER -...,-50.00
246,25-08-2025,À catégoriser,Retrait d'espèces,RETRAIT DISTRIBUTEUR BNP PARIBAS DU 24/08/25 1...,-20.00
329,16-06-2025,À catégoriser,Virement émis,VIREMENT INSTANTANE EMIS VERS JULIA-MARIE P - ...,-110.00
396,28-04-2025,À catégoriser,Virement émis,VIREMENT ETRANGER /BEN 1/DYLAN RIGAL/BIC HBUKG...,-35.64
397,28-04-2025,À catégoriser,Virement émis,VIREMENT INSTANTANE EMIS VERS KEVIN RIZZOTTO -...,-15.00
405,23-04-2025,À catégoriser,Virement émis,VIREMENT INSTANTANE EMIS VERS MARINA F - MOTIF...,-11.00
451,24-03-2025,À catégoriser,Virement émis,VIREMENT VERS MR PENNER-LACOMPTE DOUGLAS - MOT...,-20.00
483,10-03-2025,À catégoriser,Retrait d'espèces,RETRAIT DISTRIBUTEUR CAISSE D EPARGNE HAU DU 0...,-40.00

In [15]:
expense['abs_amount'] = expense['amount'].abs()
chart_expense_df = expense.groupby('category')['abs_amount'].sum().reset_index()


chart_expense_df

                    category  abs_amount
0  Abonnements et Telephonie       17.95
1            Autres Dépenses     1129.00
2                     Banque     1153.12
3            Impôts et Taxes      304.00
4                   Logement     2647.11
5         Loisirs et Sorties     2582.17
6                      Santé      126.91
7    Transports et Véhicules     1953.29
8            Vie Quotidienne     4184.21
9              À catégoriser     4366.64

In [16]:
test = expense.groupby('category').agg(abs_amount= ('abs_amount', 'sum'), count= ('abs_amount', 'count')).reset_index()

In [17]:
test

                    category  abs_amount  count
0  Abonnements et Telephonie       17.95      1
1            Autres Dépenses     1129.00      3
2                     Banque     1153.12     19
3            Impôts et Taxes      304.00      4
4                   Logement     2647.11      6
5         Loisirs et Sorties     2582.17    122
6                      Santé      126.91      7
7    Transports et Véhicules     1953.29     54
8            Vie Quotidienne     4184.21    185
9              À catégoriser     4366.64     13