# Python spending app

In [2]:
import pandas as pd
import numpy as np

In [5]:
transactions = pd.read_excel(
    "data/transactions.xls",
    skiprows= 2
)

In [57]:
transactions

,Date operation,Categorie operation,Sous Categorie operation,Libelle operation,Montant operation,Pointage operation,Commentaire operation
0,31-03-2026,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00,NaN,NaN
1,31-03-2026,Revenus,Virement reçu,VIREMENT DE MME KATHERINE COUTIN MOTIF: PAYME...,35.00,NaN,NaN
2,31-03-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB SONNY S PIZZA DU 27/03/26 A PARIS ...,-35.00,NaN,NaN
3,31-03-2026,Vie Quotidienne,"Achats, shopping",PAIEMENT CB BREIZH SAINT-GE DU 27/03/26 A SAIN...,-19.05,NaN,NaN
4,31-03-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LA CARAVANE DU 27/03/26 A PARIS 11...,-13.00,NaN,NaN
...,...,...,...,...,...,...,...
110,05-01-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LS RIM CAFE (FRANCE) DU 02/01/26 -...,-18.00,NaN,NaN
111,05-01-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB TROP BON VIET DU 31/12/25 A ST GER...,-18.00,NaN,NaN
112,05-01-2026,Banque,Frais bancaires,COMMISSIONS COTISATION A UNE OFFRE GROUPEE DE ...,-10.43,NaN,NaN
113,02-01-2026,Revenus,Virement reçu,VIREMENT DE FRANCE TRAVAIL DR IDF ALLOCA MOTI...,1230.00,NaN,NaN
114,02-01-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB CAFE JULES DU 31/12/25 A SAINT GER...,-21.00,NaN,NaN

In [58]:
columns = transactions.columns.to_list()

In [59]:
columns

['Date operation',
 'Categorie operation',
 'Sous Categorie operation',
 'Libelle operation',
 'Montant operation',
 'Pointage operation',
 'Commentaire operation']

In [10]:
col_map = {'Date operation' : 'date',
           'Categorie operation' : 'category',
           'Sous Categorie operation' : 'subcategory',
           'Libelle operation' : 'label',
           'Montant operation' : 'amount',
           'Pointage operation' : 'status',
           'Commentaire operation' : 'comment'} 

transactions = transactions.rename(columns= col_map)

transactions

,date,category,subcategory,label,amount,status,comment
0,31-03-2026,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00,NaN,NaN
1,31-03-2026,Revenus,Virement reçu,VIREMENT DE MME KATHERINE COUTIN MOTIF: PAYME...,35.00,NaN,NaN
2,31-03-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB SONNY S PIZZA DU 27/03/26 A PARIS ...,-35.00,NaN,NaN
3,31-03-2026,Vie Quotidienne,"Achats, shopping",PAIEMENT CB BREIZH SAINT-GE DU 27/03/26 A SAIN...,-19.05,NaN,NaN
4,31-03-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LA CARAVANE DU 27/03/26 A PARIS 11...,-13.00,NaN,NaN
...,...,...,...,...,...,...,...
110,05-01-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LS RIM CAFE (FRANCE) DU 02/01/26 -...,-18.00,NaN,NaN
111,05-01-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB TROP BON VIET DU 31/12/25 A ST GER...,-18.00,NaN,NaN
112,05-01-2026,Banque,Frais bancaires,COMMISSIONS COTISATION A UNE OFFRE GROUPEE DE ...,-10.43,NaN,NaN
113,02-01-2026,Revenus,Virement reçu,VIREMENT DE FRANCE TRAVAIL DR IDF ALLOCA MOTI...,1230.00,NaN,NaN
114,02-01-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB CAFE JULES DU 31/12/25 A SAINT GER...,-21.00,NaN,NaN

In [61]:
transactions.columns.tolist()

['date', 'category', 'subcategory', 'label', 'amount', 'status', 'comment']

In [62]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         115 non-null    str
 1   category     115 non-null    str
 2   subcategory  115 non-null    str
 3   label        115 non-null    str
 4   amount       115 non-null    float64
 5   status       0 non-null      float64
 6   comment      0 non-null      float64
dtypes: float64(3), str(4)
memory usage: 6.4 KB

In [66]:
transactions.to_csv("data/test.csv")

In [21]:
tester = pd.read_excel("data/test_length.xls",
                       skiprows= 2
)

tester = tester.rename(columns= col_map)

In [22]:
tester = tester.drop(columns= ['status', 'comment'])

In [23]:
tester = tester.dropna()

tester

,date,category,subcategory,label,amount
0,31-03-2026,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00
1,31-03-2026,Revenus,Virement reçu,VIREMENT DE MME KATHERINE COUTIN MOTIF: PAYME...,35.00
2,31-03-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB SONNY S PIZZA DU 27/03/26 A PARIS ...,-35.00
3,31-03-2026,Vie Quotidienne,"Achats, shopping",PAIEMENT CB BREIZH SAINT-GE DU 27/03/26 A SAIN...,-19.05
4,31-03-2026,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LA CARAVANE DU 27/03/26 A PARIS 11...,-13.00
...,...,...,...,...,...
484,10-03-2025,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LE LOBBY BAR DU 07/03/25 A LILLE -...,-12.00
485,10-03-2025,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB PHOENICIA DU 09/03/25 A LILLE - CA...,-9.50
486,10-03-2025,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-5.00
487,10-03-2025,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB MAXICOFFEE NORD DU 07/03/25 A NEUV...,-0.70
488,10-03-2025,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-0.30

In [25]:
tester['date'] = pd.to_datetime(tester['date'], format= "%d-%m-%Y")

In [26]:
tester

,date,category,subcategory,label,amount
0,2026-03-31,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00
1,2026-03-31,Revenus,Virement reçu,VIREMENT DE MME KATHERINE COUTIN MOTIF: PAYME...,35.00
2,2026-03-31,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB SONNY S PIZZA DU 27/03/26 A PARIS ...,-35.00
3,2026-03-31,Vie Quotidienne,"Achats, shopping",PAIEMENT CB BREIZH SAINT-GE DU 27/03/26 A SAIN...,-19.05
4,2026-03-31,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LA CARAVANE DU 27/03/26 A PARIS 11...,-13.00
...,...,...,...,...,...
484,2025-03-10,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LE LOBBY BAR DU 07/03/25 A LILLE -...,-12.00
485,2025-03-10,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB PHOENICIA DU 09/03/25 A LILLE - CA...,-9.50
486,2025-03-10,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-5.00
487,2025-03-10,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB MAXICOFFEE NORD DU 07/03/25 A NEUV...,-0.70
488,2025-03-10,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-0.30

In [ ]:
tester['type'] = tester['amount'].apply(lambda x : "Income" if x > 0 else "Expense")

In [32]:
tester

,date,category,subcategory,label,amount,type
0,2026-03-31,Loisirs et Sorties,"Divertissements, sorties culturelles",PAIEMENT CB LESPETITESFLECH DU 30/03/26 A 11 P...,-39.00,Expense
1,2026-03-31,Revenus,Virement reçu,VIREMENT DE MME KATHERINE COUTIN MOTIF: PAYME...,35.00,Income
2,2026-03-31,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB SONNY S PIZZA DU 27/03/26 A PARIS ...,-35.00,Expense
3,2026-03-31,Vie Quotidienne,"Achats, shopping",PAIEMENT CB BREIZH SAINT-GE DU 27/03/26 A SAIN...,-19.05,Expense
4,2026-03-31,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LA CARAVANE DU 27/03/26 A PARIS 11...,-13.00,Expense
...,...,...,...,...,...,...
484,2025-03-10,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB LE LOBBY BAR DU 07/03/25 A LILLE -...,-12.00,Expense
485,2025-03-10,Loisirs et Sorties,"Restaurants, bars",PAIEMENT CB PHOENICIA DU 09/03/25 A LILLE - CA...,-9.50,Expense
486,2025-03-10,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-5.00,Expense
487,2025-03-10,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB MAXICOFFEE NORD DU 07/03/25 A NEUV...,-0.70,Expense
488,2025-03-10,Vie Quotidienne,"Alimentation, supermarché",PAIEMENT CB LA GOURMANDISE DU 07/03/25 A LILLE...,-0.30,Expense

In [36]:
tester["category"].unique()

<ArrowStringArray>
[       'Loisirs et Sorties',                   'Revenus',
           'Vie Quotidienne',             'À catégoriser',
   'Transports et Véhicules',           'Autres Dépenses',
                     'Santé',                    'Banque',
           'Impôts et Taxes',                  'Logement',
 'Abonnements et Telephonie']
Length: 11, dtype: str

In [43]:
def is_savings(row):
    if row['amount'] < 0 and row['category'] == 'Banque':
        return 'épargne'
    elif row['amount'] < 0 :
        return 'dépense'
    else:
        return 'revenu'
    
tester['label'] = tester.apply(is_savings, axis= 1)

In [45]:
tester[tester['label'] == 'épargne']

          date category      subcategory    label   amount     type
40  2026-03-03   Banque  Frais bancaires  épargne   -11.04  Expense
79  2026-02-03   Banque  Frais bancaires  épargne   -11.04  Expense
112 2026-01-05   Banque  Frais bancaires  épargne   -10.43  Expense
139 2025-12-08   Banque  Banque - Autres  épargne  -150.00  Expense
154 2025-12-02   Banque  Frais bancaires  épargne   -10.43  Expense
155 2025-11-28   Banque  Banque - Autres  épargne  -200.00  Expense
169 2025-11-17   Banque  Banque - Autres  épargne  -200.00  Expense
190 2025-11-04   Banque  Frais bancaires  épargne   -10.43  Expense
191 2025-11-03   Banque          Épargne  épargne -1000.00  Expense
197 2025-10-31   Banque          Épargne  épargne -2000.00  Expense
200 2025-10-30   Banque          Épargne  épargne -2300.00  Expense
219 2025-10-02   Banque  Frais bancaires  épargne   -10.43  Expense
234 2025-09-03   Banque          Épargne  épargne -1670.00  Expense
236 2025-09-02   Banque  Frais bancaires  épargne   -10.43  Expense
240 2025-08-29   Banque  Frais bancaires  épargne   -24.00  Expense
244 2025-08-18   Banque          Épargne  épargne -6000.00  Expense
246 2025-08-04   Banque  Frais bancaires  épargne    -8.77  Expense
247 2025-07-31   Banque          Épargne  épargne   -30.00  Expense
276 2025-07-02   Banque  Frais bancaires  épargne    -8.77  Expense
350 2025-06-03   Banque  Frais bancaires  épargne    -8.77  Expense
388 2025-05-05   Banque  Frais bancaires  épargne    -8.77  Expense
407 2025-04-11   Banque  Banque - Autres  épargne  -150.00  Expense
412 2025-04-07   Banque  Banque - Autres  épargne  -300.00  Expense
423 2025-04-02   Banque  Frais bancaires  épargne    -8.77  Expense